# preload = ~/Pictures/Wallpapers/frieren-turning.jpg
# preload = ~/Pictures/Wallpapers/mikasa-scarf-art.jpg
# preload = ~/Pictures/Wallpapers/arch-girl.png
# preload = ~/Pictures/Wallpapers/town-night-sunset-digital.jpg

wallpaper {
  monitor = 
  # path = ~/Pictures/Wallpapers/anime-girl-blue-hair-nature-pond-butterfly.jpg
  # path = ~/Pictures/Wallpapers/chisa.jpg
  path = ~/Pictures/Wallpapers/town-night-sunset-digital.jpg
  fit_mode = cover
}
# wallpaper = ,~/Pictures/Wallpapers/lynae.jpg
